# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_lambda <- function(lam0, distSq, kappa, farOut, notOper, nthreads) {
    .Call(`_scrmove_get_lambda`, lam0, distSq, kappa, farOut, notOper, nthreads)
}

get_lambda_nou <- function(lam0, distSq, sigma, farOut, notOper, nthreads) {
    .Call(`_scrmove_get_lambda_nou`, lam0, distSq, sigma, farOut, notOper, nthreads)
}

get_lambda_noK <- function(lam0, distSq, kappa, farOut, trapOper, nthreads) {
    .Call(`_scrmove_get_lambda_noK`, lam0, distSq, kappa, farOut, trapOper, nthreads)
}

get_ld_y_n <- function(y, lambda, nthreads) {
    .Call(`_scrmove_get_ld_y_n`, y, lambda, nthreads)
}

get_ld_y_nK <- function(y, lambda, nthreads) {
    .Call(`_scrmove_get_ld_y_nK`, y, lambda, nthreads)
}

get_ld_y <- function(y, lambda, z, M) {
    .Call(`_scrmove_get_ld_y`, y, lambda, z, M)
}

get_ld_y_noK <- function(y, lambda, nthreads) {
    .Call(`_scrmove_get_ld_y_noK`, y, lambda, nthreads)
}

get_distSq_ux <- function(u, x, nthreads) {
    .Call(`_scrmove_get_distSq_ux`, u, x, nthreads)
}

get_qstar_cam <- function(nsim, x, K, sigma, rho, lam0, kappa, buffer, maxDistSq, notOper, nthreads) {
    .Call(`_scrmove_get_qstar_cam`, nsim, x, K, sigma, rho, lam0, kappa, buffer, maxDistSq, notOper, nthreads)
}

get_ld_ydet_aug <- function(nsim, s1, s2, x, K, sigma, rho, lam0, kappa, maxDistSq, notOper, nthreads) {
    .Call(`_scrmove_get_ld_ydet_aug`, nsim, s1, s2, x, K, sigma, rho, lam0, kappa, maxDistSq, notOper, nthreads)
}

get_qstar_cam_nomove <- function(nsim, x, K, lam0, kappa, buffer, maxDistSq, trapOper, nthreads) {
    .Call(`_scrmove_get_qstar_cam_nomove`, nsim, x, K, lam0, kappa, buffer, maxDistSq, trapOper, nthreads)
}

